const eye = [
  { id: "1", wt: "11", element: "bored" },
  { id: "2", wt: "12", element: "surprised" },
  { id: "3", wt: "13", element: "sad" },
  { id: "4", wt: "14", element: "laughing" },
  { id: "5", wt: "15", element: "in tears" },
  { id: "6", wt: "16", element: "angry" },
  { id: "7", wt: "17", element: "tired" },
  { id: "8", wt: "18", element: "thinking" },
  { id: "9", wt: "19", element: "winking" },
  { id: "10", wt: "20", element: "crazy" },
  { id: "11", wt: "21", element: "closed" },
  { id: "12", wt: "22", element: "in love" },
  { id: "13", wt: "39", element: "x eyes" },
  { id: "14", wt: "40", element: "btc" },
  { id: "15", wt: "41", element: "hypnotized" },
  { id: "16", wt: "42", element: "bloodshot" },
  { id: "17", wt: "43", element: "ghost eyes" },
  { id: "18", wt: "44", element: "black ghost eyes" },
  { id: "19", wt: "45", element: "popped eye" },
  { id: "20", wt: "80", element: "snake eyes" },
  { id: "21", wt: "81", element: "red laser" },
  { id: "22", wt: "82", element: "lime laser" },
  { id: "23", wt: "83", element: "purple laser" },
  { id: "24", wt: "84", element: "blue laser" },
  { id: "25", wt: "175", element: "trippy" },
  { id: "26", wt: "176", element: "fire" },
  { id: "27", wt: "177", element: "cyborg" },
  { id: "28", wt: "178", element: "mm ghost eyes" },
];

const mouth = [
  { id: "1", wt: "11", element: "bored" },
  { id: "2", wt: "12", element: "smile" },
  { id: "3", wt: "13", element: "tongue out" },
  { id: "4", wt: "14", element: "side grin" },
  { id: "5", wt: "15", element: "oh" },
  { id: "6", wt: "16", element: "knocked out tooth" },
  { id: "7", wt: "17", element: "light shave" },
  { id: "8", wt: "18", element: "angry grin" },
  { id: "9", wt: "19", element: "big smile" },
  { id: "10", wt: "20", element: "cigarette" },
  { id: "11", wt: "21", element: "silver grills" },
  { id: "12", wt: "38", element: "rage" },
  { id: "13", wt: "39", element: "rainbow grills" },
  { id: "14", wt: "40", element: "medical mask" },
  { id: "15", wt: "41", element: "underwater respirator" },
  { id: "16", wt: "42", element: "joint" },
  { id: "17", wt: "43", element: "bandana" },
  { id: "18", wt: "44", element: "cigar" },
  { id: "19", wt: "79", element: "gold grills" },
  { id: "20", wt: "80", element: "graffiti mask" },
  { id: "21", wt: "81", element: "ninja mask" },
  { id: "22", wt: "82", element: "hannya mask" },
  { id: "23", wt: "173", element: "diamond grills" },
  { id: "24", wt: "174", element: "vampire" },
  { id: "25", wt: "175", element: "mm grills" },
];

const fur = [
  { id: "1", wt: "11", element: "black" },
  { id: "2", wt: "12", element: "royal blue" },
  { id: "3", wt: "13", element: "sky blue" },
  { id: "4", wt: "14", element: "velvet" },
  { id: "5", wt: "15", element: "purple" },
  { id: "6", wt: "16", element: "light purple" },
  { id: "7", wt: "17", element: "fuchsia" },
  { id: "8", wt: "18", element: "pink" },
  { id: "9", wt: "19", element: "brown" },
  { id: "10", wt: "20", element: "cream" },
  { id: "11", wt: "21", element: "red" },
  { id: "12", wt: "22", element: "orange" },
  { id: "13", wt: "23", element: "yellow" },
  { id: "14", wt: "24", element: "white" },
  { id: "15", wt: "41", element: "gold" },
  { id: "16", wt: "42", element: "silver" },
  { id: "17", wt: "43", element: "shell nacre" },
  { id: "18", wt: "44", element: "marble" },
  { id: "19", wt: "45", element: "snake scales" },
  { id: "20", wt: "46", element: "tiger" },
  { id: "21", wt: "47", element: "jaguar" },
  { id: "22", wt: "82", element: "crystal" },
  { id: "23", wt: "83", element: "purple crystal" },
  { id: "24", wt: "84", element: "teal crystal" },
  { id: "25", wt: "85", element: "pink crystal" },
  { id: "26", wt: "86", element: "black crystal" },
  { id: "27", wt: "87", element: "lime crystal" },
  { id: "28", wt: "178", element: "trippy" },
  { id: "29", wt: "179", element: "lava" },
  { id: "30", wt: "180", element: "mm crystal" },
];

const holding = [
  { id: "1", wt: "11", element: "gym weight" },
  { id: "2", wt: "12", element: "pocket knife" },
  { id: "3", wt: "13", element: "revolver" },
  { id: "4", wt: "14", element: "wrench" },
  { id: "5", wt: "15", element: "rescue axe" },
  { id: "6", wt: "16", element: "butcher knife" },
  { id: "7", wt: "17", element: "gold stick" },
  { id: "8", wt: "18", element: "iron fist knuckles" },
  { id: "9", wt: "19", element: "butterfly knife" },
  { id: "10", wt: "20", element: "graffiti spray" },
  { id: "11", wt: "21", element: "handgun" },
  { id: "12", wt: "22", element: "double barrel shotgun" },
  { id: "13", wt: "23", element: "dollars stack" },
  { id: "14", wt: "24", element: "pen" },
  { id: "15", wt: "25", element: "sushi knife" },
  { id: "16", wt: "26", element: "lab flask" },
  { id: "17", wt: "27", element: "banana" },
  { id: "18", wt: "44", element: "kunai" },
  { id: "19", wt: "45", element: "spec ops laser rifle" },
  { id: "20", wt: "46", element: "tac laser rifle" },
  { id: "21", wt: "47", element: "laser disc" },
  { id: "22", wt: "48", element: "police laser gun" },
  { id: "23", wt: "49", element: "magic wand" },
  { id: "24", wt: "50", element: "pirate knife" },
  { id: "25", wt: "51", element: "vape" },
  { id: "26", wt: "52", element: "money gun" },
  { id: "27", wt: "53", element: "syringe" },
  { id: "28", wt: "54", element: "cigar" },
  { id: "29", wt: "89", element: "katana" },
  { id: "30", wt: "90", element: "primitive axe" },
  { id: "31", wt: "91", element: "laser spike ball" },
  { id: "32", wt: "92", element: "mm tac laser rifle" },
  { id: "33", wt: "93", element: "mm laser disc" },
  { id: "34", wt: "94", element: "tac shotgun" },
  { id: "35", wt: "95", element: "energy grenade" },
  { id: "36", wt: "96", element: "grapnel gun" },
  { id: "37", wt: "187", element: "diamond" },
  { id: "38", wt: "188", element: "pugio" },
  { id: "39", wt: "189", element: "mm spec ops rifle" },
  { id: "40", wt: "190", element: "mm diamond" },
];

const background = [
  { id: "1", wt: "11", element: "black" },
  { id: "2", wt: "12", element: "coral" },
  { id: "3", wt: "13", element: "grey" },
  { id: "4", wt: "14", element: "orange" },
  { id: "5", wt: "15", element: "pastel green" },
  { id: "6", wt: "16", element: "pink" },
  { id: "7", wt: "17", element: "purple" },
  { id: "8", wt: "18", element: "sky blue" },
  { id: "9", wt: "19", element: "white" },
  { id: "10", wt: "20", element: "yellow" },
  { id: "11", wt: "21", element: "dark grey gradient" },
  { id: "12", wt: "22", element: "green gradient" },
  { id: "13", wt: "23", element: "sky blue gradient" },
  { id: "14", wt: "40", element: "coral gradient" },
  { id: "15", wt: "41", element: "dark purple gradient" },
  { id: "16", wt: "42", element: "lime gradient" },
  { id: "17", wt: "43", element: "orange gradient" },
  { id: "18", wt: "44", element: "mix pastel gradient" },
  { id: "19", wt: "45", element: "purple gradient" },
  { id: "20", wt: "46", element: "southern gradient" },
  { id: "21", wt: "81", element: "jungle" },
  { id: "22", wt: "82", element: "mountains" },
  { id: "23", wt: "83", element: "mushrooms" },
  { id: "24", wt: "84", element: "palm beach" },
  { id: "25", wt: "85", element: "desert" },
  { id: "26", wt: "86", element: "radioactive" },
  { id: "27", wt: "177", element: "lunar" },
  { id: "28", wt: "178", element: "lava" },
  { id: "29", wt: "179", element: "city" },
  { id: "30", wt: "180", element: "mm gradient" },
];

const eyewear = [
  { id: "1", wt: "11", element: "welding goggles" },
  { id: "2", wt: "12", element: "monocle" },
  { id: "3", wt: "13", element: "sunglasses" },
  { id: "4", wt: "14", element: "star shape" },
  { id: "5", wt: "15", element: "eye patch" },
  { id: "6", wt: "16", element: "round shape" },
  { id: "7", wt: "33", element: "oversized mirror" },
  { id: "8", wt: "34", element: "neon" },
  { id: "9", wt: "35", element: "snowboard" },
  { id: "10", wt: "36", element: "swimming goggles" },
  { id: "11", wt: "71", element: "holographic" },
  { id: "12", wt: "72", element: "mm glasses" },
  {
    id: "13",
    wt: "73",
    element: "scouter power glasses",
  },
  { id: "14", wt: "164", element: "laser line" },
  {
    id: "15",
    wt: "165",
    element: "tactical night vision",
  },
  { id: "16", wt: "166", element: "mm laser line" },
];

const clothing = [
  { id: "1", wt: "11", element: "convict suit" },
  { id: "2", wt: "12", element: "biker jacket" },
  { id: "3", wt: "13", element: "cowboy jacket" },
  { id: "4", wt: "14", element: "overall" },
  { id: "5", wt: "15", element: "rescue suit" },
  { id: "6", wt: "16", element: "chef apron" },
  { id: "7", wt: "17", element: "pimp jacket" },
  { id: "8", wt: "18", element: "white undershirt" },
  { id: "9", wt: "19", element: "black undershirt" },
  { id: "10", wt: "20", element: "hoodie" },
  { id: "11", wt: "21", element: "army uniform" },
  { id: "12", wt: "22", element: "red jacket" },
  { id: "13", wt: "23", element: "kimono" },
  { id: "14", wt: "24", element: "lab coat" },
  { id: "15", wt: "25", element: "jeans jacket" },
  { id: "16", wt: "42", element: "black armor" },
  { id: "17", wt: "43", element: "deadly suit" },
  { id: "18", wt: "44", element: "astro suit" },
  { id: "19", wt: "45", element: "lightrider" },
  { id: "20", wt: "46", element: "police armor" },
  { id: "21", wt: "47", element: "hawaiian shirt" },
  { id: "22", wt: "48", element: "wizard robe" },
  { id: "23", wt: "49", element: "coat" },
  { id: "24", wt: "50", element: "shirt and vest" },
  { id: "25", wt: "51", element: "black suit" },
  { id: "26", wt: "86", element: "samurai armor" },
  { id: "27", wt: "87", element: "primitive shoulder pad" },
  { id: "28", wt: "88", element: "gladiator shoulder pad" },
  { id: "29", wt: "89", element: "mm astro suit" },
  { id: "30", wt: "90", element: "mm lightrider" },
  { id: "31", wt: "91", element: "mm hawaiian shirt" },
  { id: "32", wt: "182", element: "emperor armor" },
  { id: "33", wt: "183", element: "centurion armor" },
  { id: "34", wt: "184", element: "mm deadly suit" },
];

const headgear = [
  { id: "1", wt: "11", element: "beanie" },
  { id: "2", wt: "12", element: "biker helmet" },
  { id: "3", wt: "13", element: "cowboy hat" },
  { id: "4", wt: "14", element: "safety helmet" },
  { id: "5", wt: "15", element: "rescue helmet" },
  { id: "6", wt: "16", element: "chef toque" },
  { id: "7", wt: "17", element: "pimp hat" },
  { id: "8", wt: "18", element: "white fedora" },
  { id: "9", wt: "19", element: "black fedora" },
  { id: "10", wt: "20", element: "baseball cap" },
  { id: "11", wt: "21", element: "hip hop cap" },
  { id: "12", wt: "22", element: "tactical helmet" },
  { id: "13", wt: "23", element: "army beret" },
  { id: "14", wt: "24", element: "afro" },
  { id: "15", wt: "25", element: "general cap" },
  { id: "16", wt: "26", element: "sushi chef" },
  { id: "17", wt: "27", element: "clown wig" },
  { id: "18", wt: "44", element: "black headband" },
  { id: "19", wt: "45", element: "deadly helmet" },
  { id: "20", wt: "46", element: "astro helmet" },
  { id: "21", wt: "47", element: "lightrider helmet" },
  { id: "22", wt: "48", element: "police helmet" },
  { id: "23", wt: "49", element: "panama hat" },
  { id: "24", wt: "50", element: "wizard hat" },
  { id: "25", wt: "51", element: "pirate hat" },
  { id: "26", wt: "52", element: "top hat" },
  { id: "27", wt: "53", element: "steampunk hat" },
  { id: "28", wt: "88", element: "kasa" },
  { id: "29", wt: "89", element: "horned helmet" },
  { id: "30", wt: "90", element: "gladiator helmet" },
  { id: "31", wt: "91", element: "mm astro helmet" },
  { id: "32", wt: "92", element: "mm lightrider helmet" },
  { id: "33", wt: "183", element: "crown" },
  { id: "34", wt: "184", element: "centurion helmet" },
  { id: "35", wt: "185", element: "mm deadly helmet" },
  { id: "36", wt: "186", element: "mm afro" },
];

const earring = [
  { id: "1", wt: "11", element: "silver stud" },
  { id: "2", wt: "12", element: "silver hoop" },
  { id: "3", wt: "29", element: "gold stud" },
  { id: "4", wt: "30", element: "gold hoop" },
  { id: "5", wt: "65", element: "skull stud" },
  { id: "6", wt: "66", element: "spike stud" },
  { id: "7", wt: "157", element: "diamond stud" },
  { id: "8", wt: "158", element: "mm diamond stud" },
];

const base = [{ id: 1, wt: 0, element: "base" }];

module.exports = {
  base,
  eye,
  mouth,
  fur,
  holding,
  background,
  eyewear,
  clothing,
  headgear,
  earring,
};
